In [1]:
import numpy as np

#### Explicando .dot e @
<p> O que está acontecendo quando usa .dot
    
    Matrizes A:[1 2]
               [3 4],
               
               [5 6]
               [7 8]
    
    Matrizes B:[2 2]
               [2 2],

               [3 3]
               [3 3]
    
    Passo 1: A [linha 1] * B[matriz inteira] = C[matriz inteira]
    
    Passo 2: A [1 2]
               [3 4],
               
               [5 6]
               [7 8]  
               
               - dot pega a primeira linha, separadamente, e multiplica pela matriz. Ex: A[1,2]
    
    Passo 3: A[1,2] * B[2,2]
                       [2,2],
    
                       [3,3]
                       [3,3]
    
    Passo 4: C[(1*2) + (2*2)  (1*2)+(2*2)]
              [(1*3) + (2*3)  (1*3)+(2*3)]
    
    Sintaxe da Matriz:    
           A1[1,1]*B1[1,1] + A1[1][2]*B1[2,1]    A1[1,1]*B1[1,2] + A1[1][2]*B1[2,2]
           A1[1,1]*B2[1,1] + A1[1][2]*B2[2,1]    A1[1,1]*B2[1,2] + A1[1][2]*B2[2,2]

In [144]:
a = np.array([[[1, 2], [3, 4]],[[5,6],[7,8]]])
b = np.array([[[2, 2], [2, 2]],[[3,3],[3,3]]])
c = np.dot(a,b)


print(f"A:\n{a}\n")
print(f"B:\n{b}\n")
print(f"C:\n{c}\n")

A:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

B:
[[[2 2]
  [2 2]]

 [[3 3]
  [3 3]]]

C:
[[[[ 6  6]
   [ 9  9]]

  [[14 14]
   [21 21]]]


 [[[22 22]
   [33 33]]

  [[30 30]
   [45 45]]]]



In [134]:
a = np.array([[[1, 2], [3, 4]],[[5,6],[7,8]]])
b = np.array([[[1, 1], [1, 1]],[[1,1],[1,1]]])

r = a @ b
dot = np.dot(a,b)
print(f"A:\n{a}")
print(f"B:\n{b}")
print(f"R:\n{dot}")

#multiplica cada linha, separadamente, pela matriz inteira

A:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
B:
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
R:
[[[[ 3  3]
   [ 3  3]]

  [[ 7  7]
   [ 7  7]]]


 [[[11 11]
   [11 11]]

  [[15 15]
   [15 15]]]]
