In [1]:
import numpy as np

In [37]:
X = np.arange(6).reshape(3,2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
X_new = np.ones((X.shape[0],1))
X_new

array([[1.],
       [1.],
       [1.]])

In [28]:
b = np.c_[X,X**d]
b

array([[ 0,  1,  0,  1],
       [ 2,  3,  4,  9],
       [ 4,  5, 16, 25]])

In [39]:
d = 2
X_ones = np.ones((X.shape[0],1))
for i in range(1,d+1):
    X_new = np.c_[X,X**d]
    X_new_append = np.append(X_ones, X_new, axis = 1)
X_new_append

array([[ 1.,  0.,  1.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  9.],
       [ 1.,  4.,  5., 16., 25.]])

In [45]:
L = np.eye(self.d)
L[0][0] = 0

1.0