In [31]:
import numpy as np

In [32]:
a = np.array([[1,2],[2,3]])
a

array([[1, 2],
       [2, 3]])

In [33]:
a_ones = np.ones((a.shape[0],1)) # matriz coluna de 1's

In [34]:
d = 2
for i in range(1,d+1):
    a_new = np.c_[a,a**d]
    a_new = np.append(a_ones, a_new, axis=1) #adiciona os valores de bias na primeira coluna
a_new

array([[1., 1., 2., 1., 4.],
       [1., 2., 3., 4., 9.]])

In [35]:
L = np.identity(a.shape[1])
L

array([[1., 0.],
       [0., 1.]])

In [38]:
def _add_powers(self, X):    
    X_ones = np.ones((X.shape[0],1))  # matriz coluna de 1's
    for i in range(1,self.d+1):
        X_new = make_pipeline(PolynomialFeatures(degree = 12, include_bias = True), Ridge = 1e-5)
        #X_new = np.c_[X,X**d]
        #X_new = np.append(X_ones, X_new, axis = 1) #adiciona os valores de bias na primeira coluna
    return X_new